export const TEAM_ABBREVIATIONS = {
  "India": "IND",
  "Pakistan": "PAK",
  "Australia": "AUS",
  "England": "ENG",
  "South Africa": "SA",
  "New Zealand": "NZ",
  "West Indies": "WI",
  "Sri Lanka": "SL",
  "Bangladesh": "BAN",
  "Afghanistan": "AFG",
  "Nepal" : "NEP",
  "USA": "USA",
  "United States of America": "USA",
  "Namibia": "NAM",
  "Scotland": "SCO",
  "Ireland": "IRE",
  "Italy": "ITA",
  "UAE": "UAE",
  "United Arab Emirates": "UAE",
  "Netherlands":"NED",
  "Canada": "CAN",
  "Oman":"OMA",
  "Zimbabwe" : "ZIM"
};